version: '3.8'
services:
  jooq-db-mysql:
    image: mysql:8.0.27
#    uncomment this if you use m1
    platform: linux/amd64
    volumes:
      - test_volume:/data
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: sakila
    command:
      ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes:
  test_volume:
