version: '3'
services:
  promethus:
    image: prom/prometheus
    volumes:
      - ./infra/prometheus:/etc/prometheus
    ports:
      - '9090:9090'
  promethus-mariadb:
    image: mariadb:10.4
    depends_on:
      - 'promethus'
    volumes:
      - ./infra/mariadb/volume:/var/lib/mysql
      - ./infra/mariadb/config:/etc/mysql/mariadb.conf.d
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: test-db

  promethus-mysql-exporter:
    image: prom/mysqld-exporter
    depends_on:
      - 'promethus-mariadb'
    ports:
      - '9104:9104'
    environment:
      DATA_SOURCE_NAME: "root:passwd@(host.docker.internal:3307)/"

  grafana:
    image: grafana/grafana
    depends_on:
      - 'promethus'
    ports:
      - '3000:3000'