# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first.rules"
# - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['host.docker.internal:9090'] # Only works on Docker Desktop for Windows

  - job_name: 'docker'
      # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['192.168.65.1:9323']

  - job_name: 'mariadb-1'
    scrape_interval: "15s"
    static_configs:
      - targets: ['host.docker.internal:9104']

  - job_name: 'mariadb-2'
    scrape_interval: "15s"
    static_configs:
      - targets: ['host.docker.internal:9105']

  - job_name: 'mariadb-3'
    scrape_interval: "15s"
    static_configs:
      - targets: ['host.docker.internal:9106']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['58.142.180.87:9100']

  - job_name: 'redis_exporter_targets'
    metrics_path: /scrape
    static_configs:
      - targets:
        - redis://host.docker.internal:7000
        - redis://host.docker.internal:7001
        - redis://host.docker.internal:7002
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__ 
        replacement: 'host.docker.internal:9121'

  - job_name: 'redis_exporter'
    static_configs:
      - targets: [ 'host.docker.internal:9121' ]