version: '3'
services:
  maria-db:
    container_name: grpc-start-mariadb
    image: mariadb:10.4
    volumes:
      - ./infra/volumes/mariadb:/data
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: grpc_start
    command:
      ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']