version: '3.8'
services:
  jooq-db-mysql:
    image: mysql:8.0.27
    volumes:
      - test_volume:/data
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: jooq
    command:
      ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  test_volume: