version: '3'
services:
  galera-master-node-1:
    container_name: 'galera-master-node-1'
    image: mariadb:10.4
    volumes:
      - ./infra/mariadb/master-1/volume:/var/lib/mysql
      - ./infra/mariadb/config:/etc/mysql/mariadb.conf.d
    ports:
      - '3306:3306'
    expose:
      - '4444'
      - '4568'
      - '4567'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: test-db
    command:
      [ 'mysqld', '--wsrep_new_cluster' ]

  galera-master-node-2:
    container_name: 'galera-master-node-2'
    image: mariadb:10.4
    depends_on:
      - 'galera-master-node-1'
    volumes:
      - ./infra/mariadb/master-2/volume:/var/lib/mysql
      - ./infra/mariadb/config:/etc/mysql/mariadb.conf.d
    ports:
      - '3307:3306'
    expose:
      - '4444'
      - '4568'
      - '4567'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: test-db

  galera-master-node-3:
    container_name: 'galera-master-node-3'
    image: mariadb:10.4
    depends_on:
      - 'galera-master-node-1'
    volumes:
      - ./infra/mariadb/master-3/volume:/var/lib/mysql
      - ./infra/mariadb/config:/etc/mysql/mariadb.conf.d
    ports:
      - '3308:3306'
    expose:
      - '4444'
      - '4568'
      - '4567'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: test-db