version: '3'
services:
  jooq-db-mysql:
    image: mysql:8.0.27
    volumes:
      - ./infra/mysql/volumes:/data
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: jooq
    command:
      ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']